### ISSUE TITLE
Documentation is not clear on how to run session scoped containers

### ISSUE THREAD

**Issue by thedrow** [praekeltfoundation/seaworthy#57]
By browsing the code it seems like it is possible to redefine the docker_helper fixture to be a session scoped fixture but it is not described properly in the documentation.

How do we fix this?

**Comment by JayH5** [comment]
Changing the scope of the `docker_helper` fixture is shown in the documentation here: http://seaworthy.readthedocs.io/en/latest/api/seaworthy.pytest.fixtures.html#seaworthy.pytest.fixtures.docker_helper_fixture

But maybe that needs to be in a more obvious place in the documentation.

**Comment by thedrow** [comment]
This should be part of the tutorial somehow.

**Comment by JayH5** [comment]
@thedrow in general we probably wouldn't recommend session-scoped container fixtures as that is likely to result in too much state shared between different tests. Can you elaborate a bit more on your use case?

In the meantime, I've created #59 to clarify the effect of the `docker_helper` fixture scope in the pytest docs.

**Comment by thedrow** [comment]
I'm running a PostgresSQL container for functional tests.
Starting the container takes too much time opposed to deleting all the data or rolling back a transaction.
This is why I wanted to start the container at the session level.
