### ISSUE TITLE
Docker SDK 3.2.0 has broken log streaming

### ISSUE THREAD

**Issue by JayH5** [praekeltfoundation/seaworthy#64]
Docker SDK for Python 3.2.0 changed the internals of streaming logs in order to support cancellable streams (docker/docker-py#1965). This has broken our hacking around in the Docker client's stream logic.

Use `docker < 3.2.0` until this is fixed.

**Comment by thedrow** [comment]
Could you please release a new version that limits the dependency to below 3.2.0?

**Comment by JayH5** [comment]
@thedrow I've released Seaworthy 0.2.1.2 with the pinned dependency.
