### ISSUE TITLE
PostgreSQL container tests failing: 'role "postgres" does not exist'

### ISSUE THREAD

**Issue by JayH5** [praekeltfoundation/seaworthy#75]
This happens since docker-library/postgres#493. We execute `psql` commands under the (OS) user `postgres` which gives us the role `postgres` by default in [this code](https://github.com/praekeltfoundation/seaworthy/blob/0.3.0/seaworthy/containers/postgresql.py#L77-L87), but the `postgres` role no longer exists.

We need to pass the `-U`/`--username` with `username` attribute of the container definition object.

**Comment by jerith** [comment]
Fixed in #76.
